### ISSUE TITLE
.Net Core GetWithResponse() Error

### ISSUE THREAD

**Issue by JameyRandall** [Magenic/MAQS#23]
I am moving some API Tests over to a .Net Core project from a project that was on 4.7.1 The tests are failing on the GetWithResponse() method.  How should I get the response in a .Net Core project?

MQAS: 5.5.0

var response = this.TestObject.WebServiceDriver.GetWithResponse(APIEndpoints.ProcessDateEndpoint, "application/json", true);

 Message: 
    Test method Tests.API.APITests.ProcessDateTest threw exception: 
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
  
 Stack Trace: 
    at WebServiceDriver.ctor(HttpClient httpClient)
    at WebServiceDriverManager.GetWebServiceDriver()
    at APITests.ProcessDateTest() in Tests.cs line: 55

I have removed System.Net.Http.Formatting from the project since it is not supported in .Net Core.

**Comment by FermJacob** [comment]
Hi Jamey,

I am not able to reproduce the issue with the sample WebService test project.  Can you see if you can reproduce the issue?  You can get the extensions if you do not have them from the Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=vs-publisher-1465771.MAQSOpenFramework

![image](https://user-images.githubusercontent.com/11142854/63463311-84f39980-c422-11e9-805e-9238e78b0fca.png)

**Comment by JameyRandall** [comment]
I started the project as a MAQS Selenium project since I also have UI test in the same project.

**Comment by FermJacob** [comment]
Do you have the correct NuGet package referenced?

![image](https://user-images.githubusercontent.com/11142854/63466126-38ab5800-c428-11e9-8d97-049fabeefd39.png)

**Comment by TroyWalshProf** [comment]
Starting out with the Selenium project is the issue.

You see MAQS has a lot of dependencies.  
So if you are just doing Selenium we don't want to pull down all the email, web service, database, etc. stuff that you aren't using.

The "right" fix is to break MAQS up into the individual component nuget packages - 7 to be precise.
This would however be a pretty big breaking change for all current users and would not be done outside of a major version break.

My general rule is that I always use the composite template so I get all the potential dependencies.
