### ISSUE TITLE
SendKeys() get into a loop when we use a text followed by Keys.Enter

### ISSUE THREAD

**Issue by pjotal** [Magenic/MAQS#514]
Noticed that if we use `SendKeys("the text" + Keys.Enter)` it goes into a loop typing the text and then it fails.
The stacktrace follows below.

```
System.TimeoutException : Timed out waiting for <SendKeys>b__0 to return
  ----> System.Exception : Failed to SendKeys: SearchTextField
Locator: By.Name: q
Because: stale element reference: element is not attached to the page document
  (Session info: chrome=85.0.4183.83)

  ----> OpenQA.Selenium.StaleElementReferenceException : stale element reference: element is not attached to the page document
  (Session info: chrome=85.0.4183.83)
Stack trace:
   at Magenic.Maqs.Utilities.Helper.GenericWait.Wait[T](Func`1 waitFor, TimeSpan retryTime, TimeSpan timeout)
   at Magenic.Maqs.BaseSeleniumTest.Extensions.AbstractLazyIWebElement.SendKeys(String text)
   at Pages.GoogleSearchPage.SearchFor(String text) in /Users/xyz/Pages/GoogleSearchPage.cs:line 34
   at Tests.GoogleTests.SearchOnGoogle(String query) in /Users/xyz/UITests/GoogleTests.cs:line 25
--Exception
   at Magenic.Maqs.BaseSeleniumTest.Extensions.AbstractLazyIWebElement.ExecuteEvent(Action elementAction, String caller)
   at Magenic.Maqs.BaseSeleniumTest.Extensions.AbstractLazyIWebElement.<>c__DisplayClass51_0.<SendKeys>b__0()
   at Magenic.Maqs.Utilities.Helper.GenericWait.Wait[T](Func`1 waitFor, TimeSpan retryTime, TimeSpan timeout)
--StaleElementReferenceException
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.GetAttribute(String attributeName)
   at Magenic.Maqs.BaseSeleniumTest.SeleniumDriverManager.WebDriver_ElementValueChanged(Object sender, WebElementEventArgs e)
   at OpenQA.Selenium.Support.Events.EventFiringWebDriver.OnElementValueChanged(WebElementValueEventArgs e)
   at OpenQA.Selenium.Support.Events.EventFiringWebDriver.EventFiringWebElement.SendKeys(String text)
   at Magenic.Maqs.BaseSeleniumTest.Extensions.AbstractLazyIWebElement.<>c__DisplayClass51_1.<SendKeys>b__1()
   at Magenic.Maqs.BaseSeleniumTest.Extensions.AbstractLazyIWebElement.ExecuteEvent(Action elementAction, String caller)
```

**Comment by FermJacob** [comment]
Hi @pjotal,

Looking at the stack-trace, it looks like it is failing successfully.  Is there a way you can create a sample solution to assist us reproducing the issue?

**Comment by TroyWalshProf** [comment]
@FermJacob - I ran a couple of tests on this and it is indeed and bug.  
- Works as I designed it, but still a bug :)

The issue is that the enter key legit causes the page to refresh so lazy element detects that and tries to resubmit the send keys and gets caught in a loop. 
![image](https://user-images.githubusercontent.com/2066107/96452189-49975b00-11de-11eb-8c73-02db9ddbfedb.png)

Here is some test code that illustrates the issue
```
        [TestMethod]
        [TestCategory(TestCategories.Selenium)]
        public void LoopingSendKeys()
        {
            WebDriver.Navigate().GoToUrl("https://www.google.com/");
            LazyElement lazyRoot = new LazyElement(this.TestObject, By.Name("q"));
            lazyRoot.SendKeys("the text" + Keys.Enter);
        }
```

Here is the temporary workaround:
```
            lazyRoot.SendKeys("the text");
            lazyRoot.GetRawExistingElement().SendKeys(Keys.Enter);
```
I am hoping to propose a reasonable solution by the end of day.
