### ISSUE TITLE
Help!!! Error when use remote 

### ISSUE THREAD

**Issue by pulversss** [Magenic/MAQS#8]
Set appconfig
<add key="Browser" value="REMOTE" />

    
    <add key="BrowserSize" value="MAXIMIZE" />

    
    <add key="RemoteBrowser" value="Chrome" />
    <add key="HubUrl" value="http://{host}:4444/wd/hub" />

    
    <add key="RemotePlatform" value="win10" />

    
    <add key="RemoteBrowserVersion" value="69" />

Unable to create new service: ChromeDriverService
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:28.403Z'
System info: host: 'AUTOTESTWIN10-1', ip: '{IP}', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: unknown (SessionNotCreated)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at Magenic.Maqs.BaseSeleniumTest.SeleniumConfig.Browser(String browser)
Unable to create new service: ChromeDriverService
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:28.403Z'
System info: host: 'AUTOTESTWIN10-1', ip: '192.168.0.211', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: unknown (SessionNotCreated)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at Magenic.Maqs.BaseSeleniumTest.SeleniumConfig.Browser(String browser)
Your web driver may be out of date or unsupported.
   at Magenic.Maqs.BaseSeleniumTest.SeleniumConfig.Browser(String browser)
   at Magenic.Maqs.BaseSeleniumTest.BaseSeleniumTest.GetBrowser()
   at Magenic.Maqs.BaseSeleniumTest.BaseSeleniumTest.<CreateNewTestObject>b__6_0()
   at Magenic.Maqs.BaseSeleniumTest.SeleniumDriverManager.GetWebDriver()
   at Magenic.Maqs.BaseSeleniumTest.SeleniumTestObject.get_WebDriver()
   at PageModel.LoginPageModel.OpenLoginPage() in E:\Git\UI.AutoTest\TravelOracleSite\TravelOracle\PageModel\PageModel\LoginPageModel.cs:line 87
   at Tests.LogIn.OpenLoginPageTest() in E:\Git\UI.AutoTest\TravelOracleSite\TravelOracle\Tests\Tests\LogInTest\LogIn.cs:line 31
Your web driver may be out of date or unsupported.
   at Magenic.Maqs.BaseSeleniumTest.SeleniumConfig.Browser(String browser)
   at Magenic.Maqs.BaseSeleniumTest.BaseSeleniumTest.GetBrowser()
   at Magenic.Maqs.BaseSeleniumTest.BaseSeleniumTest.<CreateNewTestObject>b__6_0()
   at Magenic.Maqs.BaseSeleniumTest.SeleniumDriverManager.GetWebDriver()
   at Magenic.Maqs.BaseSeleniumTest.SeleniumTestObject.get_WebDriver()
   at PageModel.LoginPageModel.OpenLoginPage() in E:\Git\UI.AutoTest\TravelOracleSite\TravelOracle\PageModel\PageModel\LoginPageModel.cs:line 87
   at Tests.LogIn.OpenLoginPageTest() in E:\Git\UI.AutoTest\TravelOracleSite\TravelOracle\Tests\Tests\LogInTest\LogIn.cs:line 31
Your web driver may be out of date or unsupported.
   at Magenic.Maqs.BaseSeleniumTest.SeleniumConfig.Browser(String browser)
   at Magenic.Maqs.BaseSeleniumTest.BaseSeleniumTest.GetBrowser()
   at Magenic.Maqs.BaseSeleniumTest.BaseSeleniumTest.<CreateNewTestObject>b__6_0()
   at Magenic.Maqs.BaseSeleniumTest.SeleniumDriverManager.GetWebDriver()
   at Magenic.Maqs.BaseSeleniumTest.SeleniumTestObject.get_WebDriver()
   at PageModel.LoginPageModel.OpenLoginPage() in E:\Git\UI.AutoTest\TravelOracleSite\TravelOracle\PageModel\PageModel\LoginPageModel.cs:line 87
   at Tests.LogIn.OpenLoginPageTest() in E:\Git\UI.AutoTest\TravelOracleSite\TravelOracle\Tests\Tests\LogInTest\LogIn.cs:line 31
Your web driver may be out of date or unsupported.
   at Magenic.Maqs.BaseSeleniumTest.SeleniumConfig.Browser(String browser)
   at Magenic.Maqs.BaseSeleniumTest.BaseSeleniumTest.GetBrowser()
   at Magenic.Maqs.BaseSeleniumTest.BaseSeleniumTest.<CreateNewTestObject>b__6_0()
   at Magenic.Maqs.BaseSeleniumTest.SeleniumDriverManager.GetWebDriver()
   at Magenic.Maqs.BaseSeleniumTest.SeleniumTestObject.get_WebDriver()
   at PageModel.LoginPageModel.OpenLoginPage() in E:\Git\UI.AutoTest\TravelOracleSite\TravelOracle\PageModel\PageModel\LoginPageModel.cs:line 87
   at Tests.LogIn.OpenLoginPageTest() in E:\Git\UI.AutoTest\TravelOracleSite\TravelOracle\Tests\Tests\LogInTest\LogIn.cs:line 31
Test failed
Unable to create new service: ChromeDriverService
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:28.403Z'
System info: host: 'AUTOTESTWIN10-1', ip: '{IP}', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: unknown (SessionNotCreated)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute

Log truncated: To get complete log, select 'Copy All' from the right click menu and then paste into a text editor like Notepad.

**Comment by billros** [comment]
Check your Grid configuration.
Do you have the latest version of ChromeDriver.exe accessible to the Selenium Standalone Server on the node(s)?

The line:
Driver info: driver.version: unknown (SessionNotCreated)
Implies it never launched the chromedriver.exe.
Try checking the log on the node for more details of what went wrong.

**Comment by pulversss** [comment]
Hello!
I use https://www.guru99.com/introduction-to-selenium-grid.html for setup grid.
Yes, I have a real driver, it is there where the server is a Selenium. Also I'll write it on startup -Dwebdriver. ... ..

config node -
{
  "capabilities":
  [
    {
      "browserName": "firefox",
      "marionette": true,
      "maxInstances": 3,
      "seleniumProtocol": "WebDriver"
    },
    {
      "browserName": "chrome",
	  "platform": "win10",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver"
    },
    {
      "browserName": "internet explorer",
      "platform": "WINDOWS",
      "maxInstances": 0,
      "seleniumProtocol": "WebDriver"
    },
    {
      "browserName": "safari",
      "technologyPreview": false,
      "platform": "MAC",
      "maxInstances": 0,
      "seleniumProtocol": "WebDriver"
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 5,
  "port": 5555,
  "register": true,
  "registerCycle": 5000,
  "hub": "http://192.168.0.211:4444",
  "nodeStatusCheckTimeout": 5000,
  "nodePolling": 5000,
  "role": "node",
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2,
  "debug": false,
  "servlets" : [],
  "withoutServlets": [],
  "custom": {}
}


config hub 
{
  "port": 4444,
  "newSessionWaitTimeout": -1,
  "servlets" : [],
  "withoutServlets": [],
  "custom": {},
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "registry": "org.openqa.grid.internal.DefaultGridRegistry",
  "throwOnCapabilityNotPresent": true,
  "cleanUpCycle": 5000,
  "role": "hub",
  "debug": false,
  "browserTimeout": 0,
  "timeout": 1800
}

**Comment by pulversss** [comment]
Thanks you
