### ISSUE TITLE
Magenic.Maqs 6.4.1 do not works after ChromeDriver update from v91 to v93

### ISSUE THREAD

**Issue by denhaandrei** [Magenic/MAQS#800]
Magenic.Maqs 6.4.0 - worked fine with ChromeDriver 91.0.4472.101.
After 09/01/21 ended support for ChromeDriver v91, we updated Chrome Webdriver to 93.0.4577.6300 and Magenic.Maqs to 6.4.1 and tests stopped working.
Can you tell me what the problem is?

```
Starting ChromeDriver 93.0.4577.63 (ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}) on port 1086
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Failed ValidChangePasswordTest [1 m 1 s]
Error Message:
Test method Tests.LoginTests.ChangePasswordPageTests.ValidChangePasswordTest threw exception: 
OpenQA.Selenium.WebDriverException: Your web driver may be out of date or unsupported. ---> OpenQA.Selenium.WebDriverException: Your web driver may be out of date or unsupported. ---> OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:1086/session timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out.
Stack Trace:
at System.Net.HttpWebRequest.GetResponse()
at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
--- End of inner exception stack trace ---
at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.<>c__DisplayClass7_0.<GetChromeDriver>b__0()
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.CreateDriver(Func`1 createFunction, Boolean retry)
--- End of inner exception stack trace ---
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.CreateDriver(Func`1 createFunction, Boolean retry)
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.GetChromeDriver(TimeSpan commandTimeout, ChromeOptions chromeOptions, String size)
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.GetBrowserWithDefaultConfiguration(BrowserType browser)
--- End of inner exception stack trace ---
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.GetBrowserWithDefaultConfiguration(BrowserType browser)
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.GetDefaultBrowser()
at Magenic.Maqs.BaseSeleniumTest.BaseSeleniumTest.GetBrowser()
at Magenic.Maqs.BaseSeleniumTest.BaseSeleniumTest.<CreateNewTestObject>b__6_0()
at Magenic.Maqs.BaseSeleniumTest.SeleniumDriverManager.GetWebDriver()
at Magenic.Maqs.BaseSeleniumTest.BaseSeleniumPageModel..ctor(SeleniumTestObject testObject)
at Models.WebPage.BasePageModel..ctor(SeleniumTestObject testObject) in ...\Models\BasePageModel.cs:line 23
at Models.LoginPageModel..ctor(SeleniumTestObject testObject) in ...\WebPage\LoginPageModel.cs:line 23
at Tests.LoginTests.ChangePasswordPageTests.ValidChangePasswordTest() in ...\Tests\LoginTests\ChangePasswordPageTests.cs:line 54
Standard Output Messages:
The HTTP request to the remote WebDriver server for URL http://localhost:1086/session timed out after 60 seconds.
at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.<>c__DisplayClass7_0.<GetChromeDriver>b__0()
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.CreateDriver(Func`1 createFunction, Boolean retry)
The operation has timed out.
at System.Net.HttpWebRequest.GetResponse()
at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)

 Your web driver may be out of date or unsupported.
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.CreateDriver(Func`1 createFunction, Boolean retry)
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.GetChromeDriver(TimeSpan commandTimeout, ChromeOptions chromeOptions, String size)
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.GetBrowserWithDefaultConfiguration(BrowserType browser)
The HTTP request to the remote WebDriver server for URL http://localhost:1086/session timed out after 60 seconds.
at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.<>c__DisplayClass7_0.<GetChromeDriver>b__0()
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.CreateDriver(Func`1 createFunction, Boolean retry)
The operation has timed out.
at System.Net.HttpWebRequest.GetResponse()
at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
```

**Comment by denhaandrei** [comment]
Hi All, I found how to fix this issue. Use the following configuration with your ChromeDriver:

```
public class BaseTests : BaseSeleniumTest
{
        protected override IWebDriver GetBrowser()
        {
            var newOptions = WebDriverFactory.GetDefaultChromeOptions();
            newOptions.AddArgument("--no-sandbox");
            newOptions.AddArgument("--disable-gpu");

            return WebDriverFactory.GetChromeDriver(TimeSpan.FromSeconds(60), newOptions, "MAXIMIZE");
        }
...
```
